---
# PLAY PARA CONFIGURACAO DA VM
- hosts: cliente_1
  name: Configurando a VM
  remote_user: vagrant
  become: yes
  tasks:
    - name: Ajustando Timezone
      timezone:
        name: America/Sao_Paulo

    - name: Gerar Chave SSH
      openssh_keypair:
        path: /home/vagrant/.ssh/id_rsa
        owner: vagrant
        group: vagrant

    - name: Ajustando o Arquivo de Configuração do Ansible
      replace:
        path: /etc/ansible/ansible.cfg
        regexp: '^#host_key_checking = True'
        replace: 'host_key_checking = False'


    - name: Certifique-se de que a chave do repositório está instalada
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Garantir que o docker registry esteja disponível
      apt_repository: repo='deb https://download.docker.com/linux/ubuntu bionic stable' state=present

    - name: Garantir que o docker e as dependências estejam instalados
      apt: name=docker-ce update_cache=yes

    # Uncomment the following to enable insecure registries with Docker
    #- name: ensure docker can use insecure registries in 10.11.0.0/16
    #  lineinfile: "dest=/etc/default/docker regexp=^DOCKER_OPTS line=DOCKER_OPTS='--insecure-registry 10.11.0.0/16'"

    - service: name=docker state=restarted

    - name: Instalação de Pacotes
      apt:
        update_cache: yes
        pkg:
          - vim
