# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ## Escolha da Box
  config.vm.box = "roboxes/alpine312"

  ##Máquina Client
  config.vm.define 'cliente_2' do |client|
  client.vm.network :private_network, ip: "10.20.30.40"  
    client.vm.hostname = "client"
  #config.vm.network "forwarded_port", guest: 8080, host: 80
    # Configurações de Size da VM
    client.vm.provider "virtualbox" do |v|
      v.name = "client"
      v.memory = 1024
      v.cpus = 2
    end
  end
end
